[[schools]]
name = "University of Life"
award = "BSc (Hons) Political Sciences 2:1"
years = "1978 - 1981"

[[schools]]
name = "University of Life"
award = "BSc (Hons) Political Sciences 2:1"
years = "1978 - 1981"